export type MenuItem = {
  id: string
  name: string
  price: number
  category: string
  description?: string
  image: string
  isPopular?: boolean
  isNew?: boolean
  sizes?: { name: string; price: number }[]
}

export const menuItems: MenuItem[] = [
  // Fries
  {
    id: "fries-1",
    name: "Loaded Fries (Full)",
    price: 650,
    category: "Fries",
    description: "Crispy fries loaded with cheese, sauces and toppings",
    image: "/loaded-cheese-fries.jpg",
    isPopular: true,
  },
  {
    id: "fries-2",
    name: "Loaded Fries (Half)",
    price: 400,
    category: "Fries",
    description: "Half portion of loaded fries",
    image: "/loaded-cheese-fries.jpg",
  },
  {
    id: "fries-3",
    name: "Pizza Cheeze Fries",
    price: 700,
    category: "Fries",
    description: "Fries with pizza-style cheese topping",
    image: "/loaded-cheese-fries.jpg",
  },
  {
    id: "fries-4",
    name: "Mayo Garlic Fries",
    price: 400,
    category: "Fries",
    description: "Fries with creamy mayo garlic sauce",
    image: "/loaded-cheese-fries.jpg",
  },
  {
    id: "fries-5",
    name: "Simple Fries (Full)",
    price: 300,
    category: "Fries",
    description: "Classic golden crispy fries",
    image: "/loaded-cheese-fries.jpg",
  },
  {
    id: "fries-6",
    name: "Simple Fries (Half)",
    price: 170,
    category: "Fries",
    description: "Half portion of simple fries",
    image: "/loaded-cheese-fries.jpg",
  },
  {
    id: "fries-7",
    name: "Mexcian Bread",
    price: 850,
    category: "Fries",
    description: "Special Mexican-style bread",
    image: "/loaded-cheese-fries.jpg",
  },

  // Grill Roll
  {
    id: "grill-1",
    name: "Grill Chicken Roll",
    price: 500,
    category: "Grill Roll",
    description: "Grilled chicken wrapped in fresh bread",
    image: "/chicken-roll.jpg",
    isPopular: true,
  },
  {
    id: "grill-2",
    name: "Grill BBQ Roll",
    price: 500,
    category: "Grill Roll",
    description: "BBQ chicken roll with special sauce",
    image: "/chicken-roll.jpg",
  },
  {
    id: "grill-3",
    name: "Crispy Chicken Roll",
    price: 480,
    category: "Grill Roll",
    description: "Crispy fried chicken roll",
    image: "/chicken-roll.jpg",
  },
  {
    id: "grill-4",
    name: "Hot Wings",
    price: 400,
    category: "Grill Roll",
    description: "Spicy hot chicken wings - 8 pieces",
    image: "/hot-wings.jpg",
    sizes: [
      { name: "8 pieces", price: 400 },
      { name: "12 pieces", price: 600 },
    ],
  },
  {
    id: "grill-5",
    name: "Chicken Nuggets",
    price: 350,
    category: "Grill Roll",
    description: "Crispy chicken nuggets - 6 pieces",
    image: "/chicken-nuggets.jpg",
    sizes: [
      { name: "6 pieces", price: 350 },
      { name: "12 pieces", price: 700 },
    ],
  },
  {
    id: "grill-6",
    name: "Zinger Pic",
    price: 250,
    category: "Grill Roll",
    description: "Single crispy zinger piece",
    image: "/zinger-piece.jpg",
  },
  {
    id: "grill-7",
    name: "Cheese Slice",
    price: 60,
    category: "Grill Roll",
    description: "Extra cheese slice",
    image: "/cheese-slice.jpg",
  },
  {
    id: "grill-8",
    name: "Extra Bread",
    price: 50,
    category: "Grill Roll",
    description: "Additional bread",
    image: "/bread.jpg",
  },
  {
    id: "grill-9",
    name: "Extra Sauce",
    price: 30,
    category: "Grill Roll",
    description: "Extra sauce portion",
    image: "/sauce.jpg",
  },

  // Regular Pizza
  {
    id: "pizza-1",
    name: "Tikka Pizza",
    price: 2400,
    category: "Pizza",
    description: "Chicken tikka with special spices",
    image: "/delicious-pizza-slice.jpg",
    isPopular: true,
    sizes: [
      { name: "Small", price: 650 },
      { name: "Medium", price: 1000 },
      { name: "Large", price: 1500 },
      { name: "Family", price: 2400 },
    ],
  },
  {
    id: "pizza-2",
    name: "Fajita Pizza",
    price: 2400,
    category: "Pizza",
    description: "Loaded with chicken fajita",
    image: "/delicious-pizza-slice.jpg",
    sizes: [
      { name: "Small", price: 650 },
      { name: "Medium", price: 1000 },
      { name: "Large", price: 1500 },
      { name: "Family", price: 2400 },
    ],
  },
  {
    id: "pizza-3",
    name: "Supreme Pizza",
    price: 2400,
    category: "Pizza",
    description: "Loaded with premium toppings",
    image: "/delicious-pizza-slice.jpg",
    sizes: [
      { name: "Small", price: 650 },
      { name: "Medium", price: 1000 },
      { name: "Large", price: 1500 },
      { name: "Family", price: 2400 },
    ],
  },

  // Crust Pizza
  {
    id: "pizza-crust-1",
    name: "Lazania Crust Pizza",
    price: 2800,
    category: "Pizza",
    description: "Special crust pizza with lasagna style",
    image: "/delicious-pizza-slice.jpg",
    sizes: [
      { name: "Medium", price: 1500 },
      { name: "Large", price: 1800 },
      { name: "Family", price: 2800 },
    ],
  },
  {
    id: "pizza-crust-2",
    name: "Kabab Crust Pizza",
    price: 2800,
    category: "Pizza",
    description: "Crust stuffed with kabab",
    image: "/delicious-pizza-slice.jpg",
    sizes: [
      { name: "Medium", price: 1500 },
      { name: "Large", price: 1750 },
      { name: "Family", price: 2800 },
    ],
  },
  {
    id: "pizza-crust-3",
    name: "Crown Crust Pizza",
    price: 2800,
    category: "Pizza",
    description: "Crown-style crust pizza",
    image: "/delicious-pizza-slice.jpg",
    sizes: [
      { name: "Medium", price: 1500 },
      { name: "Large", price: 1750 },
      { name: "Family", price: 2800 },
    ],
  },

  // Butt Special Pizza
  {
    id: "pizza-special-1",
    name: "Peri Peri Special Pizza",
    price: 2700,
    category: "Pizza",
    description: "Spicy peri peri flavor",
    image: "/delicious-pizza-slice.jpg",
    sizes: [
      { name: "Small", price: 700 },
      { name: "Medium", price: 1200 },
      { name: "Large", price: 1700 },
      { name: "Family", price: 2700 },
    ],
  },
  {
    id: "pizza-special-2",
    name: "Mali Boti Special Pizza",
    price: 2700,
    category: "Pizza",
    description: "With tender malai boti pieces",
    image: "/delicious-pizza-slice.jpg",
    sizes: [
      { name: "Small", price: 700 },
      { name: "Medium", price: 1200 },
      { name: "Large", price: 1700 },
      { name: "Family", price: 2700 },
    ],
  },
  {
    id: "pizza-special-3",
    name: "Butt G Special Pizza",
    price: 2700,
    category: "Pizza",
    description: "Our signature special pizza",
    image: "/delicious-pizza-slice.jpg",
    isPopular: true,
    sizes: [
      { name: "Small", price: 700 },
      { name: "Medium", price: 1200 },
      { name: "Large", price: 1700 },
      { name: "Family", price: 2700 },
    ],
  },

  // Paratha
  {
    id: "paratha-1",
    name: "Chicken Paratha",
    price: 370,
    category: "Paratha",
    description: "Paratha roll with chicken filling",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "paratha-2",
    name: "Zinger Paratha",
    price: 400,
    category: "Paratha",
    description: "Spicy zinger in paratha",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "paratha-3",
    name: "Grill Paratha",
    price: 450,
    category: "Paratha",
    description: "Grilled chicken paratha",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "paratha-4",
    name: "Malai Boti Paratha",
    price: 400,
    category: "Paratha",
    description: "Creamy malai boti in paratha",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "paratha-5",
    name: "Chicken Tikka Paratha",
    price: 380,
    category: "Paratha",
    description: "Tikka chicken paratha roll",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "paratha-6",
    name: "Kabab Paratha",
    price: 380,
    category: "Paratha",
    description: "Kabab filled paratha",
    image: "/chicken-shawarma-wrap.png",
  },

  // Shawarma
  {
    id: "shawarma-1",
    name: "Large Chicken Shawarma",
    price: 350,
    category: "Shawarma",
    description: "Large chicken shawarma wrap",
    image: "/chicken-shawarma-wrap.png",
    isPopular: true,
  },
  {
    id: "shawarma-2",
    name: "Jumbo Chicken Shawarma",
    price: 450,
    category: "Shawarma",
    description: "Extra large shawarma",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "shawarma-3",
    name: "Chicken Tikka Shawarama",
    price: 350,
    category: "Shawarma",
    description: "Tikka chicken shawarma",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "shawarma-4",
    name: "Malai Boti Shawarama",
    price: 400,
    category: "Shawarma",
    description: "Creamy malai boti shawarma",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "shawarma-5",
    name: "Chicken Kabab Shawarma",
    price: 350,
    category: "Shawarma",
    description: "Kabab shawarma wrap",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "shawarma-6",
    name: "Grill Shawarma",
    price: 450,
    category: "Shawarma",
    description: "Grilled chicken shawarma",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "shawarma-7",
    name: "Large Zinger Shawarma (Butt Special)",
    price: 400,
    category: "Shawarma",
    description: "Special zinger shawarma",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "shawarma-8",
    name: "Zinger Chicken Mix Shawarma",
    price: 450,
    category: "Shawarma",
    description: "Mixed chicken and zinger",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "shawarma-9",
    name: "Regular Chicken Shawarma",
    price: 300,
    category: "Shawarma",
    description: "Regular size chicken shawarma",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "shawarma-10",
    name: "Regular Zinger Shawarma",
    price: 350,
    category: "Shawarma",
    description: "Regular zinger shawarma",
    image: "/chicken-shawarma-wrap.png",
  },

  // Shawarma Platter
  {
    id: "platter-1",
    name: "Zinger Platter Shawarma (2 Bread Mix)",
    price: 650,
    category: "Shawarma",
    description: "Zinger platter with 2 bread",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "platter-2",
    name: "Zinger Platter Shawarma (3 Bread Regular)",
    price: 800,
    category: "Shawarma",
    description: "Zinger platter with 3 bread",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "platter-3",
    name: "Chicken Platter Shawarma (3 Bread Large)",
    price: 680,
    category: "Shawarma",
    description: "Chicken platter with 3 bread",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "platter-4",
    name: "Butt Special Chicken Platter (4 Bread)",
    price: 980,
    category: "Shawarma",
    description: "Special platter with 4 bread",
    image: "/chicken-shawarma-wrap.png",
    isPopular: true,
  },

  // Round Burger
  {
    id: "burger-1",
    name: "Zinger Burger",
    price: 350,
    category: "Burgers",
    description: "Crispy zinger patty burger",
    image: "/juicy-cheeseburger.png",
    isPopular: true,
  },
  {
    id: "burger-2",
    name: "Patty Burger",
    price: 300,
    category: "Burgers",
    description: "Classic beef patty burger",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "burger-3",
    name: "Chapli Burger",
    price: 300,
    category: "Burgers",
    description: "Traditional chapli kabab burger",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "burger-4",
    name: "Pizza Burger",
    price: 400,
    category: "Burgers",
    description: "Pizza-style burger",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "burger-5",
    name: "Pizza Patty Burger",
    price: 450,
    category: "Burgers",
    description: "Pizza burger with beef patty",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "burger-6",
    name: "Tikka Burger",
    price: 400,
    category: "Burgers",
    description: "Chicken tikka burger",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "burger-7",
    name: "Grill Burger",
    price: 450,
    category: "Burgers",
    description: "Grilled chicken burger",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "burger-8",
    name: "Chicken Burger",
    price: 320,
    category: "Burgers",
    description: "Classic chicken burger",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "burger-9",
    name: "Zinger Tower Burger",
    price: 580,
    category: "Burgers",
    description: "Double zinger tower",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "burger-10",
    name: "Zinger Patty Tower Burger",
    price: 620,
    category: "Burgers",
    description: "Zinger and patty combo tower",
    image: "/juicy-cheeseburger.png",
  },

  // Long Burger
  {
    id: "long-burger-1",
    name: "Anda Shami Burger",
    price: 170,
    category: "Burgers",
    description: "Egg and shami kabab burger",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "long-burger-2",
    name: "Anda Shami Lapata Burger",
    price: 220,
    category: "Burgers",
    description: "Special lapata style burger",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "long-burger-3",
    name: "Double Anda Double Shami Burger",
    price: 270,
    category: "Burgers",
    description: "Double egg and shami",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "long-burger-4",
    name: "Chicken Shami Burger",
    price: 270,
    category: "Burgers",
    description: "Chicken with shami kabab",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "long-burger-5",
    name: "Chicken Shami Lapata Burger",
    price: 320,
    category: "Burgers",
    description: "Chicken shami lapata style",
    image: "/juicy-cheeseburger.png",
  },
  {
    id: "long-burger-6",
    name: "Butt Special Chicken Lapata Burger",
    price: 360,
    category: "Burgers",
    description: "Our special lapata burger",
    image: "/juicy-cheeseburger.png",
  },

  // Sandwich
  {
    id: "sandwich-1",
    name: "Club Sandwich",
    price: 380,
    category: "Sandwich",
    description: "Classic club sandwich",
    image: "/sandwich.jpg",
  },
  {
    id: "sandwich-2",
    name: "Chicken Sandwich",
    price: 320,
    category: "Sandwich",
    description: "Grilled chicken sandwich",
    image: "/sandwich.jpg",
  },
  {
    id: "sandwich-3",
    name: "Butt Special Sandwich",
    price: 450,
    category: "Sandwich",
    description: "Our special sandwich",
    image: "/sandwich.jpg",
  },
  {
    id: "sandwich-4",
    name: "Malai Boti Sandwich",
    price: 400,
    category: "Sandwich",
    description: "Creamy malai boti sandwich",
    image: "/sandwich.jpg",
  },
  {
    id: "sandwich-5",
    name: "Tikka Sandwich",
    price: 380,
    category: "Sandwich",
    description: "Tikka chicken sandwich",
    image: "/sandwich.jpg",
  },
  {
    id: "sandwich-6",
    name: "Zinger Sandwich",
    price: 350,
    category: "Sandwich",
    description: "Crispy zinger sandwich",
    image: "/sandwich.jpg",
  },
  {
    id: "sandwich-7",
    name: "Grill Sandwich",
    price: 450,
    category: "Sandwich",
    description: "Grilled chicken special",
    image: "/sandwich.jpg",
  },
  {
    id: "sandwich-8",
    name: "Shami Sandwich",
    price: 250,
    category: "Sandwich",
    description: "Shami kabab sandwich",
    image: "/sandwich.jpg",
  },

  // Wrap
  {
    id: "wrap-1",
    name: "Wrap Spices",
    price: 520,
    category: "Wrap",
    description: "Spicy chicken wrap",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "wrap-2",
    name: "Mexican Wrap",
    price: 550,
    category: "Wrap",
    description: "Mexican-style wrap",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "wrap-3",
    name: "Crunchi Wrap",
    price: 480,
    category: "Wrap",
    description: "Crunchy chicken wrap",
    image: "/chicken-shawarma-wrap.png",
  },
  {
    id: "wrap-4",
    name: "Peri Peri Wrap",
    price: 520,
    category: "Wrap",
    description: "Spicy peri peri wrap",
    image: "/chicken-shawarma-wrap.png",
  },

  // Pasta
  {
    id: "pasta-1",
    name: "Creamy Pasta Full",
    price: 700,
    category: "Pasta",
    description: "Creamy white sauce pasta",
    image: "/pasta.jpg",
  },
  {
    id: "pasta-2",
    name: "Creamy Pasta Half",
    price: 400,
    category: "Pasta",
    description: "Half portion creamy pasta",
    image: "/pasta.jpg",
  },
  {
    id: "pasta-3",
    name: "Crunchy Pasta Full",
    price: 700,
    category: "Pasta",
    description: "Pasta with crunchy toppings",
    image: "/pasta.jpg",
  },
  {
    id: "pasta-4",
    name: "Crunchy Pasta Half",
    price: 400,
    category: "Pasta",
    description: "Half portion crunchy pasta",
    image: "/pasta.jpg",
  },

  // Soup
  {
    id: "soup-1",
    name: "Chicken Corn Soup Full",
    price: 500,
    category: "Soup",
    description: "Hot chicken corn soup",
    image: "/soup.jpg",
  },
  {
    id: "soup-2",
    name: "Chicken Corn Soup Half",
    price: 350,
    category: "Soup",
    description: "Half portion soup",
    image: "/soup.jpg",
  },
  {
    id: "soup-3",
    name: "Chicken Corn Soup Reg",
    price: 200,
    category: "Soup",
    description: "Regular size soup",
    image: "/soup.jpg",
  },
]

export const categories = [
  "All",
  "Burgers",
  "Pizza",
  "Shawarma",
  "Paratha",
  "Fries",
  "Grill Roll",
  "Sandwich",
  "Wrap",
  "Pasta",
  "Soup",
]
